version: '3'

services:
  mysql:
    image: mysql:5.7.13
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"    
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306      
    ports:
      - '8080:80'
  web:
    build: .
    ports:
      - "8001:80"    
    volumes:
      - ./php/:/var/www/html/     
    links:
      - mysql
    networks:
      - default